version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres-projeto-poo
    restart: always
    environment:
      POSTGRES_DB: projeto-poo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
